name: macOS Remote Desktop via Tailscale + VNC

on:
  workflow_dispatch:   # manual start

jobs:
  macos-vnc:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Tailscale
        run: |
          brew install tailscale

      - name: Authenticate with Tailscale
        run: |
          sudo tailscaled & sleep 5
          sudo tailscale up \
            --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} \
            --hostname=gh-macos-${{ github.run_id }} \
            --accept-routes \
            --accept-dns \
            --ssh \
            --timeout=30s
          echo "Tailscale IP: $(tailscale ip -4)"

      - name: Install VNC server
        run: |
          brew install --cask xquartz
          brew install tiger-vnc

      - name: Start VNC server
        run: |
          mkdir -p ~/.vnc
          echo "github123" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd

          # Start XQuartz backend
          open -a XQuartz || true
          sleep 10

          # Start VNC server on display :1 (port 5901)
          vncserver :1 -localhost no -geometry 1440x900 -depth 24

          echo "✅ VNC server started on port 5901"
          echo "🔑 Password: github123"

      - name: Keep session alive
        run: |
          echo "Tailscale + VNC are running..."
          sleep 6h
